name: Changelog Generator

on:
  workflow_dispatch:

jobs:
  fetch-and-run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Fetch last two versions of DocGenerator.py
        run: |
          git fetch --depth=1 origin ${{ github.head_ref }}
          PWD=$(git log -n 2 --follow --pretty=format:"%H" -- "docs/DocGenerator.py" | tail -n 1)
          echo "PWD : $PWD" 
          # Get the latest commit hash for the file
          SECOND_LAST_COMMIT=$( git log -n 2 --follow --pretty=format:"%H" -- ../../docs/DocGenerator.py | tail -n 1)
          echo "Previous commit hash: $SECOND_LAST_COMMIT"
          if [ -n "$SECOND_LAST_COMMIT" ]; then
            echo "Second-to-last commit hash: $SECOND_LAST_COMMIT"
            PREVIOUS_CONTENT=$(git show $SECOND_LAST_COMMIT:../../docs/DocGenerator.py)
          else
            echo "No previous commit found for the file."
          fi

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Run Python script
        run: |
          echo "$PREVIOUS_CONTENT" > previous_content.py
          python ../workflows/changelog_generator.yml ../../docs/DocGenerator.py previous_content.py v1.0 Rajkumar

      - name: Clean up
        run: rm previous_content.py

