name: Changelog Generator

on:
  workflow_dispatch:

jobs:
  fetch-and-run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Fetch last two versions of DocGenerator.py
        run: |
          git fetch --depth=1 origin ${{ github.head_ref }}
          
          # Get the latest commit hash for the file
          LATEST_COMMIT=$(git log -n 1 --pretty=format:%H -- ./docs/DocGenerator.py)

          # Get the commit hash before the latest commit for the file
          PREVIOUS_COMMIT=$(git log --pretty=format:%H --reverse $LATEST_COMMIT -- ./docs/DocGenerator.py | sed -n 2p)

          if [ -n "$PREVIOUS_COMMIT" ]; then
            echo "Previous commit hash: $PREVIOUS_COMMIT"
            PREVIOUS_CONTENT=$(git show $PREVIOUS_COMMIT:./docs/DocGenerator.py)
          else
            echo "No previous commit found for the file."
          fi

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Run Python script
        run: |
          echo "$PREVIOUS_CONTENT" > previous_content.py
          python ./.github/scripts/changelog_generator.py ./docs/DocGenerator.py previous_content.py v1.0 Rajkumar

      - name: Clean up
        run: rm previous_content.py

