name: Changelog Generator

on:
  workflow_dispatch:

jobs:
  fetch-and-run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Fetch the last two versions of DocGenerator.py
        run: |
          git fetch --depth=1 origin ${{ github.head_ref }}
          
          # Get the last two commits affecting DocGenerator.py
          COMMIT_HASHES=$(git log -n 2 --pretty=format:"%H" -- ./docs/DocGenerator.py)
          echo "Commit hashes: $COMMIT_HASHES"
          
          # Fetch content of DocGenerator.py from the last two commits
          LAST_TWO_COMMITS=$(echo "$COMMIT_HASHES" | tr '\n' ' ')
          for COMMIT in $LAST_TWO_COMMITS; do
            CONTENT=$(git show $COMMIT:./docs/DocGenerator.py)
            echo "Content from commit $COMMIT:"
            echo "$CONTENT"
          done

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Run Python script
        run: |
          echo "$PREVIOUS_CONTENT" > previous_content.py
          python .github/scripts/changelog_generator.py docs/DocGenerator.py previous_content.py v1.0 Rajkumar

      - name: Commit and Push Changes
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Username"
      
          git add changelog.yml
          git commit -m "This is the commit message"
          
          # Use the PAT for authentication
          git push https://username:${{ secrets.PAT }}@github.com/TestOrganisation14/Test.git HEAD:main

          
      - name: Clean up
        run: rm previous_content.py

