name: check 

on:
  pull_request:
    branches:
      - 'rc_*'  # Adjust this pattern to match your rc_ branch naming convention
  
jobs:
  check-base:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0  # Important: this fetches all commits and branches

    - name: Fetch base branch
      run: |
        git fetch origin rc_1.0  # Make sure to fetch rc_1.0
        git branch -a  # Debug: list all branches to verify rc_1.0 is fetched

    - name: Check for rebase requirement
      run: |
        BASE_BRANCH=rc_1.0
        HEAD_SHA=$(git rev-parse HEAD)
        BASE_SHA=$(git rev-parse $BASE_BRANCH)  # This line is failing
        COMMON_ANCESTOR=$(git merge-base $HEAD_SHA $BASE_SHA)
        
        if [ "$COMMON_ANCESTOR" = "$BASE_SHA" ]; then
          echo "Branch is up to date. No rebase needed."
        else
          echo "Branch is not up to date. Please rebase

      

      
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This permission is required for requesting the web token without which you can't access the aws 
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
