name: check 

on:
  pull_request:
    branches:
      - 'rc_*'  # Adjust this pattern to match your rc_ branch naming convention
  
jobs:
  check-rebase:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check for rebase
      run: |
        BASE_BRANCH=${{ github.event.pull_request.base.ref }}
        git fetch origin $BASE_BRANCH # Fetching the base branch explicitly
        COMMON_BASE=$(git merge-base HEAD remotes/origin/$BASE_BRANCH) # Using the remote reference
        LATEST_BASE_COMMIT=$(git rev-parse remotes/origin/$BASE_BRANCH) # Using the remote reference
        if [[ "$COMMON_BASE" == "$LATEST_BASE_COMMIT" ]]; then
          echo "Feature branch is up to date with $BASE_BRANCH."
        else
          echo "Feature branch is not rebased on top of $BASE_BRANCH. Please rebase manually."
          exit 1
        fi
      
      
      
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This permission is required for requesting the web token without which you can't access the aws 
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
